/**
 * Payment Order Model Interface
 * 
 * Represents a payment order/transaction in the system.
 * Tracks payment requests, status, and payment provider integration details.
 * Supports multiple payment providers (Razorpay, PayU, etc.)
 */

import { ObjectId } from 'mongodb';

export type PaymentOrderStatus =
  | 'pending'
  | 'processing'
  | 'completed'
  | 'failed'
  | 'cancelled'
  | 'refunded';

export type PaymentType = 'recurring' | 'one_time';

export type Currency = 'INR' | 'USD' | 'EUR' | 'GBP';

export type PaymentProvider = 'razorpay' | 'payu' | 'paddle' | 'revenuecat';

export interface IPaymentOrder {
  /**
   * MongoDB's ObjectId (auto-generated)
   */
  _id?: ObjectId;

  /**
   * User's MongoDB ObjectId who initiated this payment
   * References the User collection
   */
  userId: ObjectId | string;

  /**
   * Unique order ID (generated by our system)
   * Used as merchant transaction ID for payment providers
   */
  orderId: string;

  /**
   * Payment provider used for this order
   * Determined by config-driven routing
   */
  provider?: PaymentProvider;

  /**
   * Plan ID that user is purchasing
   */
  planId: string;

  /**
   * Billing period for this payment
   */
  billingPeriod: 'monthly' | 'yearly' | 'one_time';

  /**
   * Payment type
   */
  paymentType: PaymentType;

  // ============================================
  // Pricing Information
  // ============================================

  /**
   * Base amount before discounts/taxes
   */
  amount: number;

  /**
   * Currency code
   */
  currency: Currency;

  /**
   * Discount amount (if coupon applied)
   * Default: 0
   */
  discountAmount?: number;

  /**
   * Tax amount (GST/VAT)
   * Default: 0
   */
  taxAmount?: number;

  /**
   * Total amount to be charged (amount - discount + tax)
   */
  totalAmount: number;

  /**
   * Coupon code applied (if any)
   * Optional: null if no coupon
   */
  couponCode?: string | null;

  // ============================================
  // Payment Status
  // ============================================

  /**
   * Current payment status
   */
  status: PaymentOrderStatus;

  /**
   * Error message if payment failed
   * Optional: null if no error
   */
  errorMessage?: string | null;

  /**
   * Timestamp when order expires (if not paid)
   * Orders expire after 30 minutes
   */
  expiresAt: Date;

  // ============================================
  // Payment Provider Integration Fields
  // ============================================

  /**
   * Provider payment ID (e.g., Razorpay order_id, PayU payment_id)
   * Optional: null until payment initiated
   */
  providerPaymentId?: string | null;

  /**
   * Provider transaction ID (e.g., Razorpay payment_id, PayU txnid)
   * Optional: null until provider responds
   */
  providerTransactionId?: string | null;

  /**
   * Provider signature/hash for verification
   * Optional: null until payment initiated
   */
  providerSignature?: string | null;

  /**
   * Redirect URL for checkout (provider-specific)
   * Optional: null until payment initiated
   */
  redirectUrl?: string | null;

  /**
   * Provider callback/response data (raw response from provider)
   * Stored for audit and debugging
   * Optional: null until provider responds
   */
  providerCallbackData?: Record<string, any> | null;

  /**
   * User country (for routing decisions)
   * Optional: null if not provided
   */
  country?: string | null;

  // ============================================
  // Legacy PayU Fields (for backward compatibility)
  // ============================================

  /**
   * @deprecated Use providerPaymentId instead
   * PayU payment ID (legacy field)
   */
  payuPaymentId?: string | null;

  /**
   * @deprecated Use providerTransactionId instead
   * PayU transaction ID (legacy field)
   */
  payuTransactionId?: string | null;

  /**
   * @deprecated Use providerSignature instead
   * PayU request hash (legacy field)
   */
  payuRequestHash?: string | null;

  /**
   * @deprecated Use providerSignature instead
   * PayU response hash (legacy field)
   */
  payuResponseHash?: string | null;

  /**
   * @deprecated Use redirectUrl instead
   * PayU redirect URL (legacy field)
   */
  payuRedirectUrl?: string | null;

  /**
   * @deprecated Use providerCallbackData instead
   * PayU callback data (legacy field)
   */
  payuCallbackData?: Record<string, any> | null;

  // ============================================
  // Subscription Reference
  // ============================================

  /**
   * Reference to subscription created from this payment
   * References the Subscription collection
   * Optional: null if subscription not created yet
   */
  subscriptionId?: ObjectId | string | null;

  // ============================================
  // Timestamps
  // ============================================

  /**
   * Timestamp when order was created
   */
  createdAt: Date;

  /**
   * Timestamp when payment was completed
   * Optional: null if not completed
   */
  completedAt?: Date | null;

  /**
   * Timestamp of last update
   */
  updatedAt: Date;
}

