export { baseSchemaFields, baseSchemaOptions, createBaseSchema } from './base.schema';
export * from './common';
export * from './auth';
export * from './users';
export * from './vault';
export * from './sessions';
export * from './devices';
export * from './sharing';
export * from './subscriptions';
export * from './audit';
export * from './notes';
export * from './documents';
export * from './notifications';
export { ensureAllSchemaIndexes } from './ensure-indexes';
