import type { FeatureFlagDefinition } from './types';

/** Live product features — default ON in production (kill-switch capable via admin later). */
const RELEASED_ON: FeatureFlagDefinition['defaults'] = {
  production: true,
  staging: true,
  development: true,
  'enterprise-dev': true,
};

/** Parked features — default OFF in production until launch day. */
const UNRELEASED_OFF: FeatureFlagDefinition['defaults'] = {
  production: false,
  staging: false,
  development: false,
  'enterprise-dev': false,
};

const RELEASED_CATALOG: readonly FeatureFlagDefinition[] = [
  {
    key: 'vault',
    displayName: 'Vault',
    description: 'Core password vault — logins, cards, identities, and secure items.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'browser-extension', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'favorites',
    displayName: 'Favorites',
    description: 'Starred / favorite vault items collection.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: RELEASED_ON,
  },
  {
    key: 'archive',
    displayName: 'Archive',
    description: 'Archived vault items view and restore flows.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: RELEASED_ON,
  },
  {
    key: 'secure_notes',
    displayName: 'Secure Notes',
    description: 'Secure notes item type and /notes route.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: RELEASED_ON,
  },
  {
    key: 'documents',
    displayName: 'Documents',
    description: 'Document storage item type and /documents route.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: RELEASED_ON,
  },
  {
    key: 'sharing',
    displayName: 'Sharing',
    description: 'Share vault items with other NovaSafe users (v1).',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'email_auth',
    displayName: 'Email & Password Auth',
    description: 'Email signup, login, onboarding OTP, and session auth.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['auth', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'google_oauth',
    displayName: 'Google Sign-In',
    description: 'Google OAuth login and account linking.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['auth', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'apple_oauth',
    displayName: 'Apple Sign-In',
    description: 'Apple OAuth login and account linking.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['auth', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'two_factor_auth',
    displayName: 'Two-Factor Authentication',
    description: 'Account-level TOTP 2FA verification on login.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['auth', 'web-app', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'browser_extension',
    displayName: 'Browser Extension',
    description: 'Browser extension pairing, autofill, and session handoff (v1).',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['browser-extension', 'web-app', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'subscriptions',
    displayName: 'Subscriptions (Pro)',
    description: 'RevenueCat billing, Pro entitlements, and account billing UI.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'mobile-api', 'admin-panel'],
    defaults: RELEASED_ON,
  },
  {
    key: 'device_management',
    displayName: 'Device Management',
    description: 'Trusted devices, session review, and device revocation.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'account_security',
    displayName: 'Security Center',
    description: 'Account security dashboard, password health, and security settings.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: RELEASED_ON,
  },
  {
    key: 'account_activity',
    displayName: 'Account Activity',
    description: 'User-facing login and security activity timeline.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'password_recovery',
    displayName: 'Password Recovery',
    description: 'Account recovery center and password reset flows.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['auth', 'web-app', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'password_history',
    displayName: 'Password History',
    description: 'Pro entitlement for full password version history on vault items.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['web-app', 'mobile', 'mobile-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'status_page',
    displayName: 'Status Page',
    description: 'Public system status page and incident visibility.',
    owner: 'platform',
    category: 'platform',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['landing', 'mobile-api', 'admin-panel', 'admin-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'admin_users',
    displayName: 'Admin Users',
    description: 'Admin panel user management and RBAC.',
    owner: 'platform',
    category: 'platform',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'admin_blog',
    displayName: 'Admin Blog',
    description: 'Blog CMS in the admin panel.',
    owner: 'platform',
    category: 'platform',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'admin_changelog',
    displayName: 'Admin Changelog',
    description: 'Product changelog editor in the admin panel.',
    owner: 'platform',
    category: 'platform',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: RELEASED_ON,
  },
  {
    key: 'admin_status',
    displayName: 'Admin Status',
    description: 'Status page incident management in the admin panel.',
    owner: 'platform',
    category: 'platform',
    tier: 'personal',
    lifecycle: 'released',
    introducedIn: '1.0.0',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: RELEASED_ON,
  },
];

const UNRELEASED_CATALOG: readonly FeatureFlagDefinition[] = [
  {
    key: 'passkeys',
    displayName: 'Passkeys',
    description: 'WebAuthn / passkey vault items and authentication flows.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'auth', 'mobile', 'mobile-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'otp',
    displayName: 'TOTP Authenticator',
    description: 'Built-in TOTP generator and authenticator vault items.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'auth', 'mobile'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'teams',
    displayName: 'Teams',
    description: 'Teams workspaces, shared vaults, and team admin experiences.',
    owner: 'platform',
    category: 'product',
    tier: 'teams',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'admin-panel', 'mobile-api', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'enterprise',
    displayName: 'Enterprise',
    description: 'Enterprise tier console, policies, and org-wide controls.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'admin-panel', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'sharing_v2',
    displayName: 'Sharing v2',
    description: 'Next-generation secure sharing flows and UI.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'audit_logs',
    displayName: 'Audit Logs',
    description: 'Enterprise audit log ingestion and admin visibility.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'admin_console',
    displayName: 'Admin Console',
    description: 'Extended admin panel modules beyond core user management.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'browser_extension_v2',
    displayName: 'Browser Extension v2',
    description: 'Next-generation browser extension autofill and offline vault.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['browser-extension', 'mobile-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'activity_logs',
    displayName: 'Activity Logs',
    description: 'User and admin activity timeline in the control plane.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'scim',
    displayName: 'SCIM Provisioning',
    description: 'SCIM user and group provisioning for enterprise IdPs.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-api'],
    defaults: UNRELEASED_OFF,
  },
  {
    key: 'sso',
    displayName: 'SSO',
    description: 'SAML/OIDC enterprise single sign-on for auth and admin.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    lifecycle: 'unreleased',
    introducedIn: 'unreleased',
    clientSurfaces: ['auth', 'admin-api'],
    defaults: UNRELEASED_OFF,
  },
];

/** Canonical feature flag catalog — validated at service startup. */
export const FEATURE_FLAG_CATALOG: readonly FeatureFlagDefinition[] = [
  ...RELEASED_CATALOG,
  ...UNRELEASED_CATALOG,
];

export const RELEASED_FEATURE_FLAG_KEYS = RELEASED_CATALOG.map((entry) => entry.key);
export const UNRELEASED_FEATURE_FLAG_KEYS = UNRELEASED_CATALOG.map((entry) => entry.key);
