import type { FeatureFlagDefinition } from './types';

const PRODUCT_OFF: FeatureFlagDefinition['defaults'] = {
  production: false,
  staging: false,
  development: false,
  'enterprise-dev': false,
};

/** Canonical feature flag catalog — validated at service startup. */
export const FEATURE_FLAG_CATALOG: readonly FeatureFlagDefinition[] = [
  {
    key: 'passkeys',
    displayName: 'Passkeys',
    description: 'WebAuthn / passkey vault items and authentication flows.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'auth', 'mobile', 'mobile-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'otp',
    displayName: 'TOTP Authenticator',
    description: 'Built-in TOTP generator and authenticator vault items.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'auth', 'mobile'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'teams',
    displayName: 'Teams',
    description: 'Teams workspaces, shared vaults, and team admin experiences.',
    owner: 'platform',
    category: 'product',
    tier: 'teams',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'admin-panel', 'mobile-api', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'enterprise',
    displayName: 'Enterprise',
    description: 'Enterprise tier console, policies, and org-wide controls.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'admin-panel', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'sharing_v2',
    displayName: 'Sharing v2',
    description: 'Next-generation secure sharing flows and UI.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    introducedIn: 'unreleased',
    clientSurfaces: ['web-app', 'mobile'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'audit_logs',
    displayName: 'Audit Logs',
    description: 'Enterprise audit log ingestion and admin visibility.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'admin_console',
    displayName: 'Admin Console',
    description: 'Extended admin panel modules beyond core user management.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'browser_extension_v2',
    displayName: 'Browser Extension v2',
    description: 'Next-generation browser extension autofill and offline vault.',
    owner: 'platform',
    category: 'product',
    tier: 'personal',
    introducedIn: 'unreleased',
    clientSurfaces: ['browser-extension', 'mobile-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'activity_logs',
    displayName: 'Activity Logs',
    description: 'User and admin activity timeline in the control plane.',
    owner: 'platform',
    category: 'platform',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-panel', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'scim',
    displayName: 'SCIM Provisioning',
    description: 'SCIM user and group provisioning for enterprise IdPs.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['admin-api'],
    defaults: PRODUCT_OFF,
  },
  {
    key: 'sso',
    displayName: 'SSO',
    description: 'SAML/OIDC enterprise single sign-on for auth and admin.',
    owner: 'platform',
    category: 'product',
    tier: 'enterprise',
    introducedIn: 'unreleased',
    clientSurfaces: ['auth', 'admin-api'],
    defaults: PRODUCT_OFF,
  },
];
